### ISSUE TITLE
Could not load file or assembly 'Topshelf.Autofac, Version=4.0.0.0

### ISSUE THREAD

**Issue by mrafea-sa** [alexandrnikitin/Topshelf.Autofac#15]
Dear alexandr nikitin
Version=4.0.0.0 always give the following Error , version 3.1 Work !
Topshelf.HostFactory Error: 0 : An exception occurred creating the host, System.IO.FileLoadException: Could not load file or assembly 'Topshelf.Autofac, Version=4.0.0.0, Culture=neutral, PublicKeyToken=ebfabbe7fb167e88' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'Topshelf.Autofac, Version=4.0.0.0, Culture=neutral, PublicKeyToken=ebfabbe7fb167e88' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
Please be informed ,
My Application use the following packages
<packages>
  <package id="Autofac" version="4.8.1" targetFramework="net461" />
  <package id="Autofac.Wcf" version="4.1.0" targetFramework="net461" />
  <package id="GreenPipes" version="2.1.3" targetFramework="net461" />
  <package id="MassTransit" version="5.2.0" targetFramework="net461" />
  <package id="MassTransit.Autofac" version="5.2.0" targetFramework="net461" />
  <package id="MassTransit.RabbitMQ" version="5.2.0" targetFramework="net461" />
  <package id="MassTransit.SerilogIntegration" version="5.2.0" targetFramework="net461" />
  <package id="Microsoft.Diagnostics.Tracing.EventRegister" version="1.1.28" targetFramework="net461" />
  <package id="Microsoft.Diagnostics.Tracing.EventSource" version="1.1.28" targetFramework="net461" />
  <package id="Microsoft.Diagnostics.Tracing.EventSource.Redist" version="1.1.28" targetFramework="net461" />
  <package id="NewId" version="3.0.1" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net461" />
  <package id="Newtonsoft.Json.Bson" version="1.0.1" targetFramework="net461" />
  <package id="RabbitMQ.Client" version="5.1.0" targetFramework="net461" />
  <package id="Serilog" version="2.7.1" targetFramework="net461" />
  <package id="Serilog.Enrichers.Environment" version="2.1.2" targetFramework="net461" />
  <package id="Serilog.Enrichers.Process" version="2.0.1" targetFramework="net461" />
  <package id="Serilog.Enrichers.Thread" version="3.0.0" targetFramework="net461" />
  <package id="Serilog.Sinks.File" version="4.0.0" targetFramework="net461" />
  <package id="Serilog.Sinks.RollingFile" version="3.3.0" targetFramework="net461" />
  <package id="System.Reflection.Emit.Lightweight" version="4.3.0" targetFramework="net461" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net461" />
  <package id="Topshelf" version="4.1.0" targetFramework="net461" />
  <package id="Topshelf.Autofac" version="3.1.1" targetFramework="net461" />
  <package id="Topshelf.Serilog" version="4.1.0" targetFramework="net461" />
</packages>
Thanks , best regards

**Comment by alexandrnikitin** [comment]
@mrafea-sa Thank you for reporting this. I can reproduce it. I'm looking into.

**Comment by alexandrnikitin** [comment]
This happens because [Delay signing was enabled](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/delay-sign-assembly) I disabled it.

**Comment by alexandrnikitin** [comment]
@mrafea-sa I published `4.0.1` and unlisted `4.0.0`. Please give it a try.
